# Generated by Django 4.2.7 on 2023-11-28 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=255)),
                ('hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
                ('in_clinic_fee', models.IntegerField(blank=True, null=True)),
                ('video_fee', models.IntegerField(blank=True, null=True)),
                ('audio_fee', models.IntegerField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='doctor/profile')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='doctor/profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='treatments/icon')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='treatments/icon')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_treatments', to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/thumbnail')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_blog', to='doctor.doctor')),
            ],
        ),
    ]
