# # Generated by Django 4.2.7 on 2023-12-01 06:04

# from django.db import migrations

from django.db import migrations


def create_treatments_item(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    treatments_model = apps.get_model("doctor", "Treatments")

    treatments_item = [
        {
            "title": "Allergy and Immunology",
            "description": "Specialists in allergy and immunology work with both adult and pediatric patients suffering from allergies and diseases of the respiratory tract or immune system. They may help patients suffering from common diseases such as asthma, food and drug allergies, immune deficiencies, and diseases of the lung. Specialists in allergy and immunology can pursue opportunities in research, education, or clinical practice."
        },
        {
            "title": "Dermatologist",
            "description": "Dermatologists diagnose and treat conditions that affect the hair, skin, and nails. This may include treating rashes or acne, diagnosing melanoma (skin cancer), and much more. In addition to this, dermatoligists also perform many aesthetic procedures that are paid for out of pocket rather than by insurance. Such procedures include Botox injections, laser skin treatments, and more. After medical school, dermatologists must attend dermatology residency. Fellowships are not required, but some dermatologists may attend them if they choose to subspecialize in a particular aspect of dermatology. Dermatology is a very competitive field for physicians. One reason for this is that dermatologists are very well compensated.4 Typically, only the top medical students are accepted into dermatology residency programs."
        },
        {
            "title": "Anesthesiologist",
            "description": "Anesthesiologists are trained to manage patient pain and vital signs during surgery. Anesthesia care team. They also often manage medical emergencies in the hospital, such as cardiac arrest and sudden breathing problems.Aspiring anesthesiologists must attend medical school followed by a residency program for anesthesiology. There are numerous subspecialties of anesthesiology they may attend fellowships for, including anesthesia for patients with chronic pain or for patients in the ICU."
        },
        {
            "title": "Cardiologist",
            "description": "Cardiologists focus on treatment of the heart and its blood vessels. This can include the management of heart failure, cardiovascular disease, and post-operative care. Training to become a cardiologist is fairly extensive. After completing three years of internal medicine residency, aspiring cardiologists need to attend several more years of fellowship training."
        },
        {
            "title": "Family Physician",
            "description": "Family practice physicians are primary care providers who see patients of all ages and provide basic care for a variety of common ailments. They are usually the first to recognize major health problems, order diagnostic tests, and refer patients to specialists when needed. After attending medical school, family medicine physicians attend a family medicine residency program for three to five years. During this time, they will receive hands-on training in pediatric care, emergency medicine, and other areas of general medicine."
        },
        {
            "title": "Gastroenterologist",
            "description": "Gastroenterologists treat the functions and diseases of the digestive system. This field attracts physicians who enjoy doing procedures, but who also like seeing patients in an outpatient setting. Gastroenterology is another subspecialty of internal medicine. At minimum, gastroenterologists attend medical school followed by an internal medicine residency. From there, they need to attend fellowship training for gastroenterology."
        },
        {
            "title": "Geneticist",
            "description": "A geneticist is a doctor who evaluates and treats people with inherited disorders such as Huntington's disease or cystic fibrosis. Geneticists may treat patients directly or work in a laboratory setting to help diagnose patients. Some geneticists also work as genetic counselors to help counsel patients who have been diagnosed with a genetic condition. Geneticists often also conduct research into clinical genetics and patient care. Geneticists have medical degrees and have completed at least a year of residency in a primary specialty and two years of medical genetics training. They may further specialize in pediatrics, internal medicine, maternal-fetal medicine, or reproductive endocrinology and infertility."
        },
        {
            "title": "Hematologist",
            "description": "Hematologists specialize in diseases of the blood, including cancers of the blood such as leukemia and lymphoma. Hematologists also treat non-cancerous conditions like hemophilia and anemia. Hematologists work directly with patients, while hematopathologists help diagnose blood-related diseases in a laboratory. Hematologists complete four years of medical school followed by a three-year residency in a specialty such as pediatrics or internal medicine. They are also required to complete a two- to four-year fellowship in a subspecialty such as pediatric hematology/oncology or pathology."
        },
        {
            "title": "Hospice and Palliative Medicine Specialist",
            "description": "A hospice and palliative medicine specialist helps patients who have serious illnesses or are at the end of life. This type of doctor does not focus on treating or curing the illness itself but instead helps manage pain and improve quality of life. A palliative medicine specialist may work in a hospital, in a hospice center, in an outpatient setting, or in other facilities that provide end-of-life care or treat and support people with serious illnesses. After finishing medical school, a person training to be a hospice and palliative medicine specialist completes a three- to seven-year residency program in a specialty such as family medicine, pediatrics, or psychiatry. After residency, they must complete a one-year specialized training fellowship."
        },
        {
            "title": "Infectious Disease Physician",
            "description": "Infectious disease physicians deal with infections that are hard to diagnose or treat. They also treat serious infections such as the swine flu, bird flu, HIV/AIDS, and other infectious diseases. After medical school, infectious disease physicians must attend an internal medicine residency followed by fellowship training for infectious diseases."
        },
        {
            "title": "Internal Medicine Physician",
            "description": "General internists provide primary care to adult patients. Internists usually have more hospital-based training than family practitioners. They may have an office-based practice or work as a hospitalist primarily seeing patients in the hospital.These physicians attend medical school followed by an internal medicine residency.Internists may then choose to pursue a fellowship to subspecialize in a variety of other areas, like endocrinology (hormone-related conditions) or cardiology (heart-related issues)."
        },
        {
            "title": "Nephrologist",
            "description": "Nephrologists treat kidney disease and prescribe dialysis for those experiencing kidney failure. After medical school, these physicians attend an internal medicine residency program. They are then required to attend fellowship training for nephrology."
        },
        {
            "title": "Neurologist",
            "description": "Neurologists are doctors who take care of patients with medical conditions that affect the brain, spine, or nerves. Neurology frequently asked questions. They see patients who have complex medical disorders such as Parkinson's disease, multiple sclerosis, and neuropathy. Neurologists also take care of patients who have common problems such as migraine headaches and dizziness.Like other physicians, neurologists must attend medical school then a residency for neurology. From there, they may pursue fellowship training for a subspecialty, such as pediatric neurology or vascular neurology (related to blood vessels in the brain)."
        },
        {
            "title": "Obstetrician/Gynecologist (OB/GYN)",
            "description": "A gynecologist is a doctor who specializes in female reproductive health, including menopause and hormone problems. An obstetrician provides care for people who are pregnant. Obstetricians also are trained to deliver babies.Often, these specialities are combined, in which case the physician is referred to as an OB/GYN. At minimum, OB/GYNs must attend medical school followed by a residency program. Once their residency is complete, some continue their training with a fellowship for a subspecialty. Gynecological oncology—a field that deals with cancer of the female reproductive organs—is just one example."
        },
        {
            "title": "Oncologist",
            "description": "Oncology is a subspecialty of internal medicine that has three main areas: medical, surgical, or radiation oncology. Oncologists take care of patients who have cancer by treating the disease itself, as well as the symptoms it causes.Often, oncologists take part in clinical trials using new and experimental treatments for cancers that are otherwise incurable. Oncologists attend medical school followed by an oncology residency. There are also fellowships for subspecialties of oncology, like pediatric oncology (children's cancer) and radiation oncology (radiation treatment for cancer)."
        },
        {
            "title": "Ophthalmologist",
            "description": "Ophthalmologists are medical doctors who treat diseases or disorders of the eyes, such as cataracts and glaucoma. Vision correction that cannot be handled by an optometrist may be treated by an ophthalmologist. When necessary, ophthalmologists will also perform eye surgery.Ophthalmologists attend medical school followed by a residency for ophthalmology. They are not required to take a fellowship, although many choose to attend fellowship training for specific eye diseases or surgical procedures."
        },
        {
            "title": "Orthopedist",
            "description": "An orthopedist or orthopedic surgeon is a doctor who specializes in conditions of the musculoskeletal system, including the bones, muscles, joints, and connective tissues. These physicians see patients with injuries such as sprains, joint injuries, and broken bones. They also specialize in chronic conditions like osteoarthritis, tendonitis, dysplasia, and osteoporosis. Orthopedists diagnose and treat conditions of the musculoskeletal system, monitor patient rehabilitation, and perform surgery when necessary.Orthopedic surgeons complete a five-year residency program with the option to complete fellowship training."
        },
        {
            "title": "Osteopath",
            "description": "An osteopath is a doctor who specializes in treating the whole person. These physicians typically practice primary care medicine such as pediatrics or internal medicine. They use musculoskeletal or cranial manipulation to restore balance in body systems such as the respiratory, digestive, or nervous systems. An osteopath completes four years of basic medical school followed by three to eight years of specialty internships, residencies, and fellowships."
        },
        {
            "title": "Pathologist",
            "description": "Pathologists specialize in investigating the cause and effect of disease and injury. These physicians are trained to evaluate tissue, blood, and body fluids to help diagnose and treat illnesses. Some pathologists also examine bodies to help find the cause of death. Clinical pathologists work with blood and other body fluids in a laboratory setting, while anatomical pathologists may examine whole organs and tissues during an autopsy. Pathologists are usually trained in both clinical and anatomical pathology and may specialize in areas such as chemical pathology (including toxicology), hematology (the study of diseases of the blood), or forensic pathology. In the United States, pathologists complete medical school followed by three years of residency training."
        },
        {
            "title": "Physician Executive",
            "description": "Some physicians do not practice medicine. Instead, they take leading roles in health care policy, pharmaceutical research, or health insurance companies.Non-clinical doctors generally are required to have completed medical school and residency. They must also maintain a medical license."
        },
    ]

    for x in treatments_item:
        treatments_model.objects.create(
            title = x['title'],
            description = x['description']
        )

class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_treatments_doctor_doctortreatments'),
    ]

    operations = [
        migrations.RunPython(create_treatments_item),
    ]
